name: location_tracker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.0
  dot_navigation_bar: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_database: ^10.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_compass: ^0.8.0
  flutter_form_builder: ^9.1.1
  flutter_signin_button: ^2.0.0
  flutter_udid: ^2.0.1
  form_builder_validators: ^9.1.0
  geolocator: ^10.1.0
  getwidget: ^4.0.0
  # flutter_osm_plugin: ^0.60.5
  introduction_screen: ^3.1.12
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  latlng: ^1.0.0
  lottie: ^2.6.0
  modal_bottom_sheet: ^3.0.0-pre
  path: ^1.8.3
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  uuid: ^3.0.7
  flutter_map: ^6.0.1
  backdrop: ^0.9.1
  sliding_up_panel: ^2.0.0+1
  material_floating_search_bar_2: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottiefiles/
